### ISSUE TITLE
Styling issues with long deployment revision names

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/nr1-deployment-analyzer#13]
## Description

There seems to be some styling issues, primarily with the buttons when there are long deployment names. I use git SHA as the revision name when deploying, but this seems to push the "Filter Tags" and "Analyze" buttons mostly out of the frame. I've added screenshots below. The "View Events" button also wraps likely due to the long revision name.

## Steps to Reproduce

View the list of deployments with long revision names (such as the git SHA).

## Expected Behaviour

I can see the full text of all the buttons.

## Relevant Logs / Console output

<img width="1440" alt="Screen Shot 2020-05-20 at 9 07 05 PM" src="https://user-images.githubusercontent.com/565661/82522586-c19e0f80-9ade-11ea-87dd-a8da6c70f9cd.png">

## Your Environment

* NR1 CLI version used: N/A
* Browser name and version: Chrome 81
* Operating System and version: macOS Catalina 10.15.3

**Comment by Kav91** [comment]
Fixed in #22 thats been merged to master.
Will schedule a catalog update shortly.
