### ISSUE TITLE
App and deployments are accessible, but charts are blank

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/nr1-deployment-analyzer#2]
## 1 

I'm able to serve and access the app with no issues, however, I'm not seeing any performance data related to deployments.

 I would expect to see data similar to this:

![image](https://user-images.githubusercontent.com/9002169/67789551-2a8a4100-fa42-11e9-84bd-cc55d3282062.png)

Instead, I see this:

![image](https://user-images.githubusercontent.com/9002169/67789311-c1a2c900-fa41-11e9-9789-914ce70e6622.png)

## 2
The app doesn't seem to honor the user's timezone preferences.  I switched from Eastern to Central time in my profile and the times remained the same on the deployment markers.  

## 3
Timepicker is not functional.  Bug or feature request?

**Comment by matthewbalvanz-wf** [comment]
I noticed the same blank charts as well and did a little digging into the nerdlet code. At least for our data, a `Transaction` has an `appId` attribute, but the query being created is using `applicationId` in the query:
https://github.com/newrelic/nr1-deployment-analyzer/blob/master/nerdlets/deployment-analyzer-nerdlet/components/deployments-container.js#L64

After changing that to `appId` I was able to see the charts populate when I ran this app.

**Comment by sarabartell** [comment]
I made the changes in this pull request: https://github.com/newrelic/nr1-deployment-analyzer/pull/3

**Comment by Kav91** [comment]
@bpschmitt @matthewbalvanz-wf fixed thanks to @sarabartell 's PR #3 
It was due to NR staging account using a different application id attribute, so there is a appId attribute on some APM events and applicationId on others not sure why but I've added a fallback OR condition in the where clause just in case and bumped the version in the latest commit too.
