### ISSUE TITLE
Deployment Analyser is not loading any data

### ISSUE THREAD

**Issue by pradeepvenkatakrishnan** [newrelic/nr1-deployment-analyzer#56]
## Description

I am from one of the large UK retailer using this app. We are have several deployments in APM and Open Telemetry. The Deployment Analyzer use to show the data for last 2 years, but when i check yesterday, we could not find the deployment in the apps, but in the APM we could see a lot.

**Comment by aso1124** [comment]
Hi @pradeepvenkatakrishnan  - Thank you for reporting this; we are looking into it now. 

As a note, this application will be reaching maintenance EOL shortly, as [Change Tracking](https://docs.newrelic.com/docs/change-tracking/change-tracking-introduction/) is now available as an integrated feature in New Relic.

If there are features included in this app that aren't available in the suite of capabilities found in Change Tracking, please let us know here - we'll make those are communicated to the product manager.
